version: "3.8"

services:
  # -----------------
  # Kafka Broker 1
  # -----------------
  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1

    # External access: host port 9092 to container port 9092 (EXTERNAL Listener)
    ports:
      - "9092:9092"
    
    # Additional ports for internal communication
    expose:
      - "9093"
      - "9094"
    
    # Environment variables for Kafka Broker 1
    environment:
      KAFKA_NODE_ID: 1  # --> Unique Broker-ID
      CLUSTER_ID: "CLUSTER_UUID_12345"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9092,INTERNAL://kafka1:9093"  # --> Unique EXTERNAL Listener Port

      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9094,2@kafka2:9094,3@kafka3:9094"
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

    # Network configuration
    networks:
      - kafka-net

  # -----------------
  # Kafka Broker 2
  # -----------------
  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2

    # External access: host port 9093 to container port 9092 (EXTERNAL Listener)
    ports:
      - "9093:9092"

    # Additional ports for internal communication
    expose:
      - "9093"
      - "9094"

    # Environment variables for Kafka Broker 2  
    environment:
      KAFKA_NODE_ID: 2  # --> Unique Broker-ID
      CLUSTER_ID: "CLUSTER_UUID_12345"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9093,INTERNAL://kafka2:9093"  # --> Unique EXTERNAL Listener Port

      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9094,2@kafka2:9094,3@kafka3:9094"
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

    # Network configuration
    networks:
      - kafka-net

  # -----------------
  # Kafka Broker 3
  # -----------------
  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3

    # External access: host port 9094 to container port 9092 (EXTERNAL Listener)
    ports:
      - "9094:9092"

    # Additional ports for internal communication
    expose:
      - "9093"
      - "9094"

    # Environment variables for Kafka Broker 3
    environment:
      KAFKA_NODE_ID: 3  # --> Unique Broker-ID
      CLUSTER_ID: "CLUSTER_UUID_12345"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9094,INTERNAL://kafka3:9093"  # --> Unique EXTERNAL Listener Port

      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9094,2@kafka2:9094,3@kafka3:9094"
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

    # Network configuration
    networks:
      - kafka-net

  # -----------------
  # Kouncil (Web-GUI)
  # -----------------
  kouncil:
    image: consdata/kouncil:latest
    container_name: kouncil

    ports:
      - "8888:8080"

    # Environment variables for Kouncil
    environment:
      - bootstrapServers=kafka1:9093,kafka2:9093,kafka3:9093
      - KAFKA_BROKERS=kafka1:9093,kafka2:9093,kafka3:9093
      - kouncil.auth.active-provider=inmemory

    # Network configuration
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
